object Plugins {
    const val androidApplication = "com.android.application"
    const val androidLibrary = "com.android.library"
    const val androidConvention = "android-convention"
    const val kotlinConvention = "kotlin-convention"
    const val kotlinKapt = "kotlin-kapt"
    const val kotlinAndroid = "kotlin-android"
    const val mobileMultiplatform = "dev.icerock.mobile.multiplatform"
    const val iosFramework = "dev.icerock.mobile.multiplatform.ios-framework"
    const val mavenPublish = "maven-publish"
    const val mavenPublishConfig = "publication.maven-publish-config"
    const val signing = "signing"
    const val navigationArgs = "androidx.navigation.safeargs.kotlin"
    const val swiftPackage = "com.chromaticnoise.multiplatform-swiftpackage"
    const val kotlinMultiplatform = "org.jetbrains.kotlin.multiplatform"
    const val kotlinMultiplatformConvention = "kotlin-multiplatform-convention"
    const val kotlinSerialization = "kotlinx-serialization"
    const val resources = "dev.icerock.mobile.multiplatform-resources"
    const val sqldelight = "com.squareup.sqldelight"
    const val kotlinParcelize = "kotlin-parcelize"
}