object Plugins {
    val androidApplication = "com.android.application"
    val androidLibrary = "com.android.library"
    val kotlinKapt = "kotlin-kapt"
    val kotlinAndroid = "kotlin-android"
    val mobileMultiplatform = "dev.icerock.mobile.multiplatform"
    val iosFramework = "dev.icerock.mobile.multiplatform.ios-framework"
    val mavenPublish = "maven-publish"
    val mavenPublishConfig = "publication.maven-publish-config"
    val signing = "signing"
    val navigationArgs = "androidx.navigation.safeargs.kotlin"
    val swiftPackage = "com.chromaticnoise.multiplatform-swiftpackage"
    val kotlinMultiplatform = "org.jetbrains.kotlin.multiplatform"
    val kotlinSerialization = "kotlinx-serialization"
    val resources = "dev.icerock.mobile.multiplatform-resources"
    val sqldelight = "com.squareup.sqldelight"
    val kotlinParcelize = "kotlin-parcelize"
}